// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ASchot.Pulumi.Dbtcloud.Inputs
{

    public sealed class LegacyGroupGroupPermissionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether or not to apply this permission to all projects for this group
        /// </summary>
        [Input("allProjects", required: true)]
        public Input<bool> AllProjects { get; set; } = null!;

        /// <summary>
        /// Set of permissions to apply
        /// </summary>
        [Input("permissionSet", required: true)]
        public Input<string> PermissionSet { get; set; } = null!;

        /// <summary>
        /// Project ID to apply this permission to for this group
        /// </summary>
        [Input("projectId")]
        public Input<int>? ProjectId { get; set; }

        public LegacyGroupGroupPermissionArgs()
        {
        }
        public static new LegacyGroupGroupPermissionArgs Empty => new LegacyGroupGroupPermissionArgs();
    }
}
