// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ASchot.Pulumi.Dbtcloud.Outputs
{

    [OutputType]
    public sealed class LegacyGroupGroupPermission
    {
        /// <summary>
        /// Whether or not to apply this permission to all projects for this group
        /// </summary>
        public readonly bool AllProjects;
        /// <summary>
        /// Set of permissions to apply
        /// </summary>
        public readonly string PermissionSet;
        /// <summary>
        /// Project ID to apply this permission to for this group
        /// </summary>
        public readonly int? ProjectId;

        [OutputConstructor]
        private LegacyGroupGroupPermission(
            bool allProjects,

            string permissionSet,

            int? projectId)
        {
            AllProjects = allProjects;
            PermissionSet = permissionSet;
            ProjectId = projectId;
        }
    }
}
