// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("dbtcloud");

/**
 * Account identifier for your dbt Cloud implementation. Instead of setting the parameter, you can set the environment
 * variable `DBT_CLOUD_ACCOUNT_ID`
 */
export declare const accountId: number | undefined;
Object.defineProperty(exports, "accountId", {
    get() {
        return __config.getObject<number>("accountId") ?? utilities.getEnvNumber("DBT_CLOUD_ACCOUNT_ID");
    },
    enumerable: true,
});

/**
 * URL for your dbt Cloud deployment. Instead of setting the parameter, you can set the environment variable
 * `DBT_CLOUD_HOST_URL` - Defaults to https://cloud.getdbt.com/api
 */
export declare const hostUrl: string;
Object.defineProperty(exports, "hostUrl", {
    get() {
        return __config.get("hostUrl") ?? (utilities.getEnv("DBT_CLOUD_HOST_URL") || "https://cloud.getdbt.com/api");
    },
    enumerable: true,
});

/**
 * API token for your dbt Cloud. Instead of setting the parameter, you can set the environment variable `DBT_CLOUD_TOKEN`
 */
export declare const token: string | undefined;
Object.defineProperty(exports, "token", {
    get() {
        return __config.get("token") ?? utilities.getEnv("DBT_CLOUD_TOKEN");
    },
    enumerable: true,
});

