// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ASchot.Pulumi.Dbtcloud
{
    [Obsolete(@"Do not use! This resource is mapped from the legacy Terraform `dbt_cloud_`-prefixed resource/datasource")]
    public static class LegacyGetEnvironmentVariable
    {
        public static Task<LegacyGetEnvironmentVariableResult> InvokeAsync(LegacyGetEnvironmentVariableArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<LegacyGetEnvironmentVariableResult>("dbtcloud:index/legacyGetEnvironmentVariable:LegacyGetEnvironmentVariable", args ?? new LegacyGetEnvironmentVariableArgs(), options.WithDefaults());

        public static Output<LegacyGetEnvironmentVariableResult> Invoke(LegacyGetEnvironmentVariableInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<LegacyGetEnvironmentVariableResult>("dbtcloud:index/legacyGetEnvironmentVariable:LegacyGetEnvironmentVariable", args ?? new LegacyGetEnvironmentVariableInvokeArgs(), options.WithDefaults());
    }


    public sealed class LegacyGetEnvironmentVariableArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        [Input("projectId", required: true)]
        public int ProjectId { get; set; }

        public LegacyGetEnvironmentVariableArgs()
        {
        }
        public static new LegacyGetEnvironmentVariableArgs Empty => new LegacyGetEnvironmentVariableArgs();
    }

    public sealed class LegacyGetEnvironmentVariableInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("projectId", required: true)]
        public Input<int> ProjectId { get; set; } = null!;

        public LegacyGetEnvironmentVariableInvokeArgs()
        {
        }
        public static new LegacyGetEnvironmentVariableInvokeArgs Empty => new LegacyGetEnvironmentVariableInvokeArgs();
    }


    [OutputType]
    public sealed class LegacyGetEnvironmentVariableResult
    {
        public readonly ImmutableDictionary<string, object> EnvironmentValues;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly int ProjectId;

        [OutputConstructor]
        private LegacyGetEnvironmentVariableResult(
            ImmutableDictionary<string, object> environmentValues,

            string id,

            string name,

            int projectId)
        {
            EnvironmentValues = environmentValues;
            Id = id;
            Name = name;
            ProjectId = projectId;
        }
    }
}
