// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ASchot.Pulumi.Dbtcloud
{
    [Obsolete(@"Do not use! This resource is mapped from the legacy Terraform `dbt_cloud_`-prefixed resource/datasource")]
    public static class LegacyGetEnvironment
    {
        public static Task<LegacyGetEnvironmentResult> InvokeAsync(LegacyGetEnvironmentArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<LegacyGetEnvironmentResult>("dbtcloud:index/legacyGetEnvironment:LegacyGetEnvironment", args ?? new LegacyGetEnvironmentArgs(), options.WithDefaults());

        public static Output<LegacyGetEnvironmentResult> Invoke(LegacyGetEnvironmentInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<LegacyGetEnvironmentResult>("dbtcloud:index/legacyGetEnvironment:LegacyGetEnvironment", args ?? new LegacyGetEnvironmentInvokeArgs(), options.WithDefaults());
    }


    public sealed class LegacyGetEnvironmentArgs : global::Pulumi.InvokeArgs
    {
        [Input("environmentId", required: true)]
        public int EnvironmentId { get; set; }

        [Input("projectId", required: true)]
        public int ProjectId { get; set; }

        public LegacyGetEnvironmentArgs()
        {
        }
        public static new LegacyGetEnvironmentArgs Empty => new LegacyGetEnvironmentArgs();
    }

    public sealed class LegacyGetEnvironmentInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("environmentId", required: true)]
        public Input<int> EnvironmentId { get; set; } = null!;

        [Input("projectId", required: true)]
        public Input<int> ProjectId { get; set; } = null!;

        public LegacyGetEnvironmentInvokeArgs()
        {
        }
        public static new LegacyGetEnvironmentInvokeArgs Empty => new LegacyGetEnvironmentInvokeArgs();
    }


    [OutputType]
    public sealed class LegacyGetEnvironmentResult
    {
        public readonly int CredentialId;
        public readonly string CustomBranch;
        public readonly string DbtVersion;
        public readonly string DeploymentType;
        public readonly int EnvironmentId;
        public readonly int ExtendedAttributesId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly bool IsActive;
        public readonly string Name;
        public readonly int ProjectId;
        public readonly string Type;
        public readonly bool UseCustomBranch;

        [OutputConstructor]
        private LegacyGetEnvironmentResult(
            int credentialId,

            string customBranch,

            string dbtVersion,

            string deploymentType,

            int environmentId,

            int extendedAttributesId,

            string id,

            bool isActive,

            string name,

            int projectId,

            string type,

            bool useCustomBranch)
        {
            CredentialId = credentialId;
            CustomBranch = customBranch;
            DbtVersion = dbtVersion;
            DeploymentType = deploymentType;
            EnvironmentId = environmentId;
            ExtendedAttributesId = extendedAttributesId;
            Id = id;
            IsActive = isActive;
            Name = name;
            ProjectId = projectId;
            Type = type;
            UseCustomBranch = useCustomBranch;
        }
    }
}
