// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetGroupUsersUser {
    email: string;
    id: number;
}

export interface GetServiceTokenServiceTokenPermission {
    allProjects: boolean;
    permissionSet: string;
    projectId: number;
}

export interface GroupGroupPermission {
    /**
     * Whether or not to apply this permission to all projects for this group
     */
    allProjects: boolean;
    /**
     * Set of permissions to apply
     */
    permissionSet: string;
    /**
     * Project ID to apply this permission to for this group
     */
    projectId?: number;
}

export interface LegacyGetServiceTokenServiceTokenPermission {
    allProjects: boolean;
    permissionSet: string;
    projectId: number;
}

export interface LegacyGroupGroupPermission {
    allProjects: boolean;
    permissionSet: string;
    projectId?: number;
}

export interface LegacyServiceTokenServiceTokenPermission {
    allProjects: boolean;
    permissionSet: string;
    projectId?: number;
}

export interface ServiceTokenServiceTokenPermission {
    /**
     * Whether or not to apply this permission to all projects for this service token
     */
    allProjects: boolean;
    /**
     * Set of permissions to apply
     */
    permissionSet: string;
    /**
     * Project ID to apply this permission to for this service token
     */
    projectId?: number;
}

