// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dbtcloud

import (
	"context"
	"reflect"

	"github.com/a-schot/pulumi-dbtcloud/sdk/go/dbtcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Deprecated: Do not use! This resource is mapped from the legacy Terraform `dbt_cloud_`-prefixed resource/datasource
func LegacyGetGroup(ctx *pulumi.Context, args *LegacyGetGroupArgs, opts ...pulumi.InvokeOption) (*LegacyGetGroupResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LegacyGetGroupResult
	err := ctx.Invoke("dbtcloud:index/legacyGetGroup:LegacyGetGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking LegacyGetGroup.
type LegacyGetGroupArgs struct {
	GroupId int `pulumi:"groupId"`
}

// A collection of values returned by LegacyGetGroup.
type LegacyGetGroupResult struct {
	AssignByDefault bool `pulumi:"assignByDefault"`
	GroupId         int  `pulumi:"groupId"`
	// The provider-assigned unique ID for this managed resource.
	Id               string   `pulumi:"id"`
	IsActive         bool     `pulumi:"isActive"`
	Name             string   `pulumi:"name"`
	SsoMappingGroups []string `pulumi:"ssoMappingGroups"`
}

func LegacyGetGroupOutput(ctx *pulumi.Context, args LegacyGetGroupOutputArgs, opts ...pulumi.InvokeOption) LegacyGetGroupResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LegacyGetGroupResult, error) {
			args := v.(LegacyGetGroupArgs)
			r, err := LegacyGetGroup(ctx, &args, opts...)
			var s LegacyGetGroupResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LegacyGetGroupResultOutput)
}

// A collection of arguments for invoking LegacyGetGroup.
type LegacyGetGroupOutputArgs struct {
	GroupId pulumi.IntInput `pulumi:"groupId"`
}

func (LegacyGetGroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LegacyGetGroupArgs)(nil)).Elem()
}

// A collection of values returned by LegacyGetGroup.
type LegacyGetGroupResultOutput struct{ *pulumi.OutputState }

func (LegacyGetGroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LegacyGetGroupResult)(nil)).Elem()
}

func (o LegacyGetGroupResultOutput) ToLegacyGetGroupResultOutput() LegacyGetGroupResultOutput {
	return o
}

func (o LegacyGetGroupResultOutput) ToLegacyGetGroupResultOutputWithContext(ctx context.Context) LegacyGetGroupResultOutput {
	return o
}

func (o LegacyGetGroupResultOutput) AssignByDefault() pulumi.BoolOutput {
	return o.ApplyT(func(v LegacyGetGroupResult) bool { return v.AssignByDefault }).(pulumi.BoolOutput)
}

func (o LegacyGetGroupResultOutput) GroupId() pulumi.IntOutput {
	return o.ApplyT(func(v LegacyGetGroupResult) int { return v.GroupId }).(pulumi.IntOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LegacyGetGroupResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LegacyGetGroupResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LegacyGetGroupResultOutput) IsActive() pulumi.BoolOutput {
	return o.ApplyT(func(v LegacyGetGroupResult) bool { return v.IsActive }).(pulumi.BoolOutput)
}

func (o LegacyGetGroupResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LegacyGetGroupResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LegacyGetGroupResultOutput) SsoMappingGroups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LegacyGetGroupResult) []string { return v.SsoMappingGroups }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LegacyGetGroupResultOutput{})
}
