// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dbtcloud

import (
	"context"
	"reflect"

	"github.com/a-schot/pulumi-dbtcloud/sdk/go/dbtcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LegacyGetPrivatelinkEndpoint(ctx *pulumi.Context, args *LegacyGetPrivatelinkEndpointArgs, opts ...pulumi.InvokeOption) (*LegacyGetPrivatelinkEndpointResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LegacyGetPrivatelinkEndpointResult
	err := ctx.Invoke("dbtcloud:index/legacyGetPrivatelinkEndpoint:LegacyGetPrivatelinkEndpoint", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking LegacyGetPrivatelinkEndpoint.
type LegacyGetPrivatelinkEndpointArgs struct {
	Name                   *string `pulumi:"name"`
	PrivateLinkEndpointUrl *string `pulumi:"privateLinkEndpointUrl"`
}

// A collection of values returned by LegacyGetPrivatelinkEndpoint.
type LegacyGetPrivatelinkEndpointResult struct {
	CidrRange              string  `pulumi:"cidrRange"`
	Id                     string  `pulumi:"id"`
	Name                   *string `pulumi:"name"`
	PrivateLinkEndpointUrl *string `pulumi:"privateLinkEndpointUrl"`
	State                  int     `pulumi:"state"`
	Type                   string  `pulumi:"type"`
}

func LegacyGetPrivatelinkEndpointOutput(ctx *pulumi.Context, args LegacyGetPrivatelinkEndpointOutputArgs, opts ...pulumi.InvokeOption) LegacyGetPrivatelinkEndpointResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LegacyGetPrivatelinkEndpointResult, error) {
			args := v.(LegacyGetPrivatelinkEndpointArgs)
			r, err := LegacyGetPrivatelinkEndpoint(ctx, &args, opts...)
			var s LegacyGetPrivatelinkEndpointResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LegacyGetPrivatelinkEndpointResultOutput)
}

// A collection of arguments for invoking LegacyGetPrivatelinkEndpoint.
type LegacyGetPrivatelinkEndpointOutputArgs struct {
	Name                   pulumi.StringPtrInput `pulumi:"name"`
	PrivateLinkEndpointUrl pulumi.StringPtrInput `pulumi:"privateLinkEndpointUrl"`
}

func (LegacyGetPrivatelinkEndpointOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LegacyGetPrivatelinkEndpointArgs)(nil)).Elem()
}

// A collection of values returned by LegacyGetPrivatelinkEndpoint.
type LegacyGetPrivatelinkEndpointResultOutput struct{ *pulumi.OutputState }

func (LegacyGetPrivatelinkEndpointResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LegacyGetPrivatelinkEndpointResult)(nil)).Elem()
}

func (o LegacyGetPrivatelinkEndpointResultOutput) ToLegacyGetPrivatelinkEndpointResultOutput() LegacyGetPrivatelinkEndpointResultOutput {
	return o
}

func (o LegacyGetPrivatelinkEndpointResultOutput) ToLegacyGetPrivatelinkEndpointResultOutputWithContext(ctx context.Context) LegacyGetPrivatelinkEndpointResultOutput {
	return o
}

func (o LegacyGetPrivatelinkEndpointResultOutput) CidrRange() pulumi.StringOutput {
	return o.ApplyT(func(v LegacyGetPrivatelinkEndpointResult) string { return v.CidrRange }).(pulumi.StringOutput)
}

func (o LegacyGetPrivatelinkEndpointResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LegacyGetPrivatelinkEndpointResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LegacyGetPrivatelinkEndpointResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LegacyGetPrivatelinkEndpointResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o LegacyGetPrivatelinkEndpointResultOutput) PrivateLinkEndpointUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LegacyGetPrivatelinkEndpointResult) *string { return v.PrivateLinkEndpointUrl }).(pulumi.StringPtrOutput)
}

func (o LegacyGetPrivatelinkEndpointResultOutput) State() pulumi.IntOutput {
	return o.ApplyT(func(v LegacyGetPrivatelinkEndpointResult) int { return v.State }).(pulumi.IntOutput)
}

func (o LegacyGetPrivatelinkEndpointResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LegacyGetPrivatelinkEndpointResult) string { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LegacyGetPrivatelinkEndpointResultOutput{})
}
