// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dbtcloud

import (
	"context"
	"reflect"

	"errors"
	"github.com/a-schot/pulumi-dbtcloud/sdk/go/dbtcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// *Note*: Some upstream resources can be slow to create, so if creating a project at
// the same time as the repository, it's recommended to use the `dependsOn` meta argument.
//
// In order to find the `githubInstallationId`, you can log in to dbt Cloud, replace `<dbt_cloud_url>` by your dbt Cloud
// URL and run the following commands in the Google Chrome console:
//
// Alternatively, you can go to the page `https://<dbt_cloud_url>/api/v2/integrations/github/installations/` and read the
// value of `id`  or use the `http` provider to retrieve it automatically like in the example below.
//
// ## Example Usage
//
// ## Import
//
// Import using a project ID and repository ID found in the URL or via the API.
//
// ```sh
// $ pulumi import dbtcloud:index/repository:Repository test_repository "project_id:repository_id"
// ```
//
// ```sh
// $ pulumi import dbtcloud:index/repository:Repository test_repository 12345:6789
// ```
type Repository struct {
	pulumi.CustomResourceState

	// The Azure Dev Ops project ID. It can be retrieved via the Azure API or using the data source `getAzureDevOpsProject` and the project name - (for ADO native integration only)
	AzureActiveDirectoryProjectId pulumi.StringPtrOutput `pulumi:"azureActiveDirectoryProjectId"`
	// The Azure Dev Ops repository ID. It can be retrieved via the Azure API or using the data source `getAzureDevOpsRepository` along with the ADO Project ID and the repository name - (for ADO native integration only)
	AzureActiveDirectoryRepositoryId pulumi.StringPtrOutput `pulumi:"azureActiveDirectoryRepositoryId"`
	// If set to False (the default), the connection will fail if the service user doesn't have access to set webhooks (required for auto-triggering CI jobs). If set to True, the connection will be successful but no automated CI job will be triggered - (for ADO native integration only)
	AzureBypassWebhookRegistrationFailure pulumi.BoolPtrOutput `pulumi:"azureBypassWebhookRegistrationFailure"`
	// Public key generated by dbt when using `deployKey` clone strategy
	DeployKey pulumi.StringOutput `pulumi:"deployKey"`
	// Whether we should return the public deploy key - (for the `deployKey` strategy)
	FetchDeployKey pulumi.BoolPtrOutput `pulumi:"fetchDeployKey"`
	// Git clone strategy for the repository. Can be `deployKey` (default) for cloning via SSH Deploy Key, `githubApp` for GitHub native integration, `deployToken` for the GitLab native integration and `azureActiveDirectoryApp` for ADO native integration
	GitCloneStrategy pulumi.StringPtrOutput `pulumi:"gitCloneStrategy"`
	// Identifier for the GitHub App - (for GitHub native integration only)
	GithubInstallationId pulumi.IntPtrOutput `pulumi:"githubInstallationId"`
	// Identifier for the Gitlab project -  (for GitLab native integration only)
	GitlabProjectId pulumi.IntPtrOutput `pulumi:"gitlabProjectId"`
	// Whether the repository is active
	IsActive pulumi.BoolPtrOutput `pulumi:"isActive"`
	// Project ID to create the repository in
	ProjectId pulumi.IntOutput `pulumi:"projectId"`
	// Git URL for the repository or <Group>/<Project> for Gitlab
	RemoteUrl pulumi.StringOutput `pulumi:"remoteUrl"`
	// Credentials ID for the repository (From the repository side not the dbt Cloud ID)
	RepositoryCredentialsId pulumi.IntOutput `pulumi:"repositoryCredentialsId"`
	// Repository Identifier
	RepositoryId pulumi.IntOutput `pulumi:"repositoryId"`
}

// NewRepository registers a new resource with the given unique name, arguments, and options.
func NewRepository(ctx *pulumi.Context,
	name string, args *RepositoryArgs, opts ...pulumi.ResourceOption) (*Repository, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ProjectId == nil {
		return nil, errors.New("invalid value for required argument 'ProjectId'")
	}
	if args.RemoteUrl == nil {
		return nil, errors.New("invalid value for required argument 'RemoteUrl'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Repository
	err := ctx.RegisterResource("dbtcloud:index/repository:Repository", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRepository gets an existing Repository resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRepository(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RepositoryState, opts ...pulumi.ResourceOption) (*Repository, error) {
	var resource Repository
	err := ctx.ReadResource("dbtcloud:index/repository:Repository", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Repository resources.
type repositoryState struct {
	// The Azure Dev Ops project ID. It can be retrieved via the Azure API or using the data source `getAzureDevOpsProject` and the project name - (for ADO native integration only)
	AzureActiveDirectoryProjectId *string `pulumi:"azureActiveDirectoryProjectId"`
	// The Azure Dev Ops repository ID. It can be retrieved via the Azure API or using the data source `getAzureDevOpsRepository` along with the ADO Project ID and the repository name - (for ADO native integration only)
	AzureActiveDirectoryRepositoryId *string `pulumi:"azureActiveDirectoryRepositoryId"`
	// If set to False (the default), the connection will fail if the service user doesn't have access to set webhooks (required for auto-triggering CI jobs). If set to True, the connection will be successful but no automated CI job will be triggered - (for ADO native integration only)
	AzureBypassWebhookRegistrationFailure *bool `pulumi:"azureBypassWebhookRegistrationFailure"`
	// Public key generated by dbt when using `deployKey` clone strategy
	DeployKey *string `pulumi:"deployKey"`
	// Whether we should return the public deploy key - (for the `deployKey` strategy)
	FetchDeployKey *bool `pulumi:"fetchDeployKey"`
	// Git clone strategy for the repository. Can be `deployKey` (default) for cloning via SSH Deploy Key, `githubApp` for GitHub native integration, `deployToken` for the GitLab native integration and `azureActiveDirectoryApp` for ADO native integration
	GitCloneStrategy *string `pulumi:"gitCloneStrategy"`
	// Identifier for the GitHub App - (for GitHub native integration only)
	GithubInstallationId *int `pulumi:"githubInstallationId"`
	// Identifier for the Gitlab project -  (for GitLab native integration only)
	GitlabProjectId *int `pulumi:"gitlabProjectId"`
	// Whether the repository is active
	IsActive *bool `pulumi:"isActive"`
	// Project ID to create the repository in
	ProjectId *int `pulumi:"projectId"`
	// Git URL for the repository or <Group>/<Project> for Gitlab
	RemoteUrl *string `pulumi:"remoteUrl"`
	// Credentials ID for the repository (From the repository side not the dbt Cloud ID)
	RepositoryCredentialsId *int `pulumi:"repositoryCredentialsId"`
	// Repository Identifier
	RepositoryId *int `pulumi:"repositoryId"`
}

type RepositoryState struct {
	// The Azure Dev Ops project ID. It can be retrieved via the Azure API or using the data source `getAzureDevOpsProject` and the project name - (for ADO native integration only)
	AzureActiveDirectoryProjectId pulumi.StringPtrInput
	// The Azure Dev Ops repository ID. It can be retrieved via the Azure API or using the data source `getAzureDevOpsRepository` along with the ADO Project ID and the repository name - (for ADO native integration only)
	AzureActiveDirectoryRepositoryId pulumi.StringPtrInput
	// If set to False (the default), the connection will fail if the service user doesn't have access to set webhooks (required for auto-triggering CI jobs). If set to True, the connection will be successful but no automated CI job will be triggered - (for ADO native integration only)
	AzureBypassWebhookRegistrationFailure pulumi.BoolPtrInput
	// Public key generated by dbt when using `deployKey` clone strategy
	DeployKey pulumi.StringPtrInput
	// Whether we should return the public deploy key - (for the `deployKey` strategy)
	FetchDeployKey pulumi.BoolPtrInput
	// Git clone strategy for the repository. Can be `deployKey` (default) for cloning via SSH Deploy Key, `githubApp` for GitHub native integration, `deployToken` for the GitLab native integration and `azureActiveDirectoryApp` for ADO native integration
	GitCloneStrategy pulumi.StringPtrInput
	// Identifier for the GitHub App - (for GitHub native integration only)
	GithubInstallationId pulumi.IntPtrInput
	// Identifier for the Gitlab project -  (for GitLab native integration only)
	GitlabProjectId pulumi.IntPtrInput
	// Whether the repository is active
	IsActive pulumi.BoolPtrInput
	// Project ID to create the repository in
	ProjectId pulumi.IntPtrInput
	// Git URL for the repository or <Group>/<Project> for Gitlab
	RemoteUrl pulumi.StringPtrInput
	// Credentials ID for the repository (From the repository side not the dbt Cloud ID)
	RepositoryCredentialsId pulumi.IntPtrInput
	// Repository Identifier
	RepositoryId pulumi.IntPtrInput
}

func (RepositoryState) ElementType() reflect.Type {
	return reflect.TypeOf((*repositoryState)(nil)).Elem()
}

type repositoryArgs struct {
	// The Azure Dev Ops project ID. It can be retrieved via the Azure API or using the data source `getAzureDevOpsProject` and the project name - (for ADO native integration only)
	AzureActiveDirectoryProjectId *string `pulumi:"azureActiveDirectoryProjectId"`
	// The Azure Dev Ops repository ID. It can be retrieved via the Azure API or using the data source `getAzureDevOpsRepository` along with the ADO Project ID and the repository name - (for ADO native integration only)
	AzureActiveDirectoryRepositoryId *string `pulumi:"azureActiveDirectoryRepositoryId"`
	// If set to False (the default), the connection will fail if the service user doesn't have access to set webhooks (required for auto-triggering CI jobs). If set to True, the connection will be successful but no automated CI job will be triggered - (for ADO native integration only)
	AzureBypassWebhookRegistrationFailure *bool `pulumi:"azureBypassWebhookRegistrationFailure"`
	// Whether we should return the public deploy key - (for the `deployKey` strategy)
	FetchDeployKey *bool `pulumi:"fetchDeployKey"`
	// Git clone strategy for the repository. Can be `deployKey` (default) for cloning via SSH Deploy Key, `githubApp` for GitHub native integration, `deployToken` for the GitLab native integration and `azureActiveDirectoryApp` for ADO native integration
	GitCloneStrategy *string `pulumi:"gitCloneStrategy"`
	// Identifier for the GitHub App - (for GitHub native integration only)
	GithubInstallationId *int `pulumi:"githubInstallationId"`
	// Identifier for the Gitlab project -  (for GitLab native integration only)
	GitlabProjectId *int `pulumi:"gitlabProjectId"`
	// Whether the repository is active
	IsActive *bool `pulumi:"isActive"`
	// Project ID to create the repository in
	ProjectId int `pulumi:"projectId"`
	// Git URL for the repository or <Group>/<Project> for Gitlab
	RemoteUrl string `pulumi:"remoteUrl"`
}

// The set of arguments for constructing a Repository resource.
type RepositoryArgs struct {
	// The Azure Dev Ops project ID. It can be retrieved via the Azure API or using the data source `getAzureDevOpsProject` and the project name - (for ADO native integration only)
	AzureActiveDirectoryProjectId pulumi.StringPtrInput
	// The Azure Dev Ops repository ID. It can be retrieved via the Azure API or using the data source `getAzureDevOpsRepository` along with the ADO Project ID and the repository name - (for ADO native integration only)
	AzureActiveDirectoryRepositoryId pulumi.StringPtrInput
	// If set to False (the default), the connection will fail if the service user doesn't have access to set webhooks (required for auto-triggering CI jobs). If set to True, the connection will be successful but no automated CI job will be triggered - (for ADO native integration only)
	AzureBypassWebhookRegistrationFailure pulumi.BoolPtrInput
	// Whether we should return the public deploy key - (for the `deployKey` strategy)
	FetchDeployKey pulumi.BoolPtrInput
	// Git clone strategy for the repository. Can be `deployKey` (default) for cloning via SSH Deploy Key, `githubApp` for GitHub native integration, `deployToken` for the GitLab native integration and `azureActiveDirectoryApp` for ADO native integration
	GitCloneStrategy pulumi.StringPtrInput
	// Identifier for the GitHub App - (for GitHub native integration only)
	GithubInstallationId pulumi.IntPtrInput
	// Identifier for the Gitlab project -  (for GitLab native integration only)
	GitlabProjectId pulumi.IntPtrInput
	// Whether the repository is active
	IsActive pulumi.BoolPtrInput
	// Project ID to create the repository in
	ProjectId pulumi.IntInput
	// Git URL for the repository or <Group>/<Project> for Gitlab
	RemoteUrl pulumi.StringInput
}

func (RepositoryArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*repositoryArgs)(nil)).Elem()
}

type RepositoryInput interface {
	pulumi.Input

	ToRepositoryOutput() RepositoryOutput
	ToRepositoryOutputWithContext(ctx context.Context) RepositoryOutput
}

func (*Repository) ElementType() reflect.Type {
	return reflect.TypeOf((**Repository)(nil)).Elem()
}

func (i *Repository) ToRepositoryOutput() RepositoryOutput {
	return i.ToRepositoryOutputWithContext(context.Background())
}

func (i *Repository) ToRepositoryOutputWithContext(ctx context.Context) RepositoryOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RepositoryOutput)
}

// RepositoryArrayInput is an input type that accepts RepositoryArray and RepositoryArrayOutput values.
// You can construct a concrete instance of `RepositoryArrayInput` via:
//
//	RepositoryArray{ RepositoryArgs{...} }
type RepositoryArrayInput interface {
	pulumi.Input

	ToRepositoryArrayOutput() RepositoryArrayOutput
	ToRepositoryArrayOutputWithContext(context.Context) RepositoryArrayOutput
}

type RepositoryArray []RepositoryInput

func (RepositoryArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Repository)(nil)).Elem()
}

func (i RepositoryArray) ToRepositoryArrayOutput() RepositoryArrayOutput {
	return i.ToRepositoryArrayOutputWithContext(context.Background())
}

func (i RepositoryArray) ToRepositoryArrayOutputWithContext(ctx context.Context) RepositoryArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RepositoryArrayOutput)
}

// RepositoryMapInput is an input type that accepts RepositoryMap and RepositoryMapOutput values.
// You can construct a concrete instance of `RepositoryMapInput` via:
//
//	RepositoryMap{ "key": RepositoryArgs{...} }
type RepositoryMapInput interface {
	pulumi.Input

	ToRepositoryMapOutput() RepositoryMapOutput
	ToRepositoryMapOutputWithContext(context.Context) RepositoryMapOutput
}

type RepositoryMap map[string]RepositoryInput

func (RepositoryMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Repository)(nil)).Elem()
}

func (i RepositoryMap) ToRepositoryMapOutput() RepositoryMapOutput {
	return i.ToRepositoryMapOutputWithContext(context.Background())
}

func (i RepositoryMap) ToRepositoryMapOutputWithContext(ctx context.Context) RepositoryMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RepositoryMapOutput)
}

type RepositoryOutput struct{ *pulumi.OutputState }

func (RepositoryOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Repository)(nil)).Elem()
}

func (o RepositoryOutput) ToRepositoryOutput() RepositoryOutput {
	return o
}

func (o RepositoryOutput) ToRepositoryOutputWithContext(ctx context.Context) RepositoryOutput {
	return o
}

// The Azure Dev Ops project ID. It can be retrieved via the Azure API or using the data source `getAzureDevOpsProject` and the project name - (for ADO native integration only)
func (o RepositoryOutput) AzureActiveDirectoryProjectId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Repository) pulumi.StringPtrOutput { return v.AzureActiveDirectoryProjectId }).(pulumi.StringPtrOutput)
}

// The Azure Dev Ops repository ID. It can be retrieved via the Azure API or using the data source `getAzureDevOpsRepository` along with the ADO Project ID and the repository name - (for ADO native integration only)
func (o RepositoryOutput) AzureActiveDirectoryRepositoryId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Repository) pulumi.StringPtrOutput { return v.AzureActiveDirectoryRepositoryId }).(pulumi.StringPtrOutput)
}

// If set to False (the default), the connection will fail if the service user doesn't have access to set webhooks (required for auto-triggering CI jobs). If set to True, the connection will be successful but no automated CI job will be triggered - (for ADO native integration only)
func (o RepositoryOutput) AzureBypassWebhookRegistrationFailure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Repository) pulumi.BoolPtrOutput { return v.AzureBypassWebhookRegistrationFailure }).(pulumi.BoolPtrOutput)
}

// Public key generated by dbt when using `deployKey` clone strategy
func (o RepositoryOutput) DeployKey() pulumi.StringOutput {
	return o.ApplyT(func(v *Repository) pulumi.StringOutput { return v.DeployKey }).(pulumi.StringOutput)
}

// Whether we should return the public deploy key - (for the `deployKey` strategy)
func (o RepositoryOutput) FetchDeployKey() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Repository) pulumi.BoolPtrOutput { return v.FetchDeployKey }).(pulumi.BoolPtrOutput)
}

// Git clone strategy for the repository. Can be `deployKey` (default) for cloning via SSH Deploy Key, `githubApp` for GitHub native integration, `deployToken` for the GitLab native integration and `azureActiveDirectoryApp` for ADO native integration
func (o RepositoryOutput) GitCloneStrategy() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Repository) pulumi.StringPtrOutput { return v.GitCloneStrategy }).(pulumi.StringPtrOutput)
}

// Identifier for the GitHub App - (for GitHub native integration only)
func (o RepositoryOutput) GithubInstallationId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Repository) pulumi.IntPtrOutput { return v.GithubInstallationId }).(pulumi.IntPtrOutput)
}

// Identifier for the Gitlab project -  (for GitLab native integration only)
func (o RepositoryOutput) GitlabProjectId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Repository) pulumi.IntPtrOutput { return v.GitlabProjectId }).(pulumi.IntPtrOutput)
}

// Whether the repository is active
func (o RepositoryOutput) IsActive() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Repository) pulumi.BoolPtrOutput { return v.IsActive }).(pulumi.BoolPtrOutput)
}

// Project ID to create the repository in
func (o RepositoryOutput) ProjectId() pulumi.IntOutput {
	return o.ApplyT(func(v *Repository) pulumi.IntOutput { return v.ProjectId }).(pulumi.IntOutput)
}

// Git URL for the repository or <Group>/<Project> for Gitlab
func (o RepositoryOutput) RemoteUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *Repository) pulumi.StringOutput { return v.RemoteUrl }).(pulumi.StringOutput)
}

// Credentials ID for the repository (From the repository side not the dbt Cloud ID)
func (o RepositoryOutput) RepositoryCredentialsId() pulumi.IntOutput {
	return o.ApplyT(func(v *Repository) pulumi.IntOutput { return v.RepositoryCredentialsId }).(pulumi.IntOutput)
}

// Repository Identifier
func (o RepositoryOutput) RepositoryId() pulumi.IntOutput {
	return o.ApplyT(func(v *Repository) pulumi.IntOutput { return v.RepositoryId }).(pulumi.IntOutput)
}

type RepositoryArrayOutput struct{ *pulumi.OutputState }

func (RepositoryArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Repository)(nil)).Elem()
}

func (o RepositoryArrayOutput) ToRepositoryArrayOutput() RepositoryArrayOutput {
	return o
}

func (o RepositoryArrayOutput) ToRepositoryArrayOutputWithContext(ctx context.Context) RepositoryArrayOutput {
	return o
}

func (o RepositoryArrayOutput) Index(i pulumi.IntInput) RepositoryOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Repository {
		return vs[0].([]*Repository)[vs[1].(int)]
	}).(RepositoryOutput)
}

type RepositoryMapOutput struct{ *pulumi.OutputState }

func (RepositoryMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Repository)(nil)).Elem()
}

func (o RepositoryMapOutput) ToRepositoryMapOutput() RepositoryMapOutput {
	return o
}

func (o RepositoryMapOutput) ToRepositoryMapOutputWithContext(ctx context.Context) RepositoryMapOutput {
	return o
}

func (o RepositoryMapOutput) MapIndex(k pulumi.StringInput) RepositoryOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Repository {
		return vs[0].(map[string]*Repository)[vs[1].(string)]
	}).(RepositoryOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RepositoryInput)(nil)).Elem(), &Repository{})
	pulumi.RegisterInputType(reflect.TypeOf((*RepositoryArrayInput)(nil)).Elem(), RepositoryArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RepositoryMapInput)(nil)).Elem(), RepositoryMap{})
	pulumi.RegisterOutputType(RepositoryOutput{})
	pulumi.RegisterOutputType(RepositoryArrayOutput{})
	pulumi.RegisterOutputType(RepositoryMapOutput{})
}
