# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('dbtcloud')


class _ExportableConfig(types.ModuleType):
    @property
    def account_id(self) -> Optional[int]:
        """
        Account identifier for your dbt Cloud implementation. Instead of setting the parameter, you can set the environment
        variable `DBT_CLOUD_ACCOUNT_ID`
        """
        return __config__.get_int('accountId') or _utilities.get_env_int('DBT_CLOUD_ACCOUNT_ID')

    @property
    def host_url(self) -> str:
        """
        URL for your dbt Cloud deployment. Instead of setting the parameter, you can set the environment variable
        `DBT_CLOUD_HOST_URL` - Defaults to https://cloud.getdbt.com/api
        """
        return __config__.get('hostUrl') or (_utilities.get_env('DBT_CLOUD_HOST_URL') or 'https://cloud.getdbt.com/api')

    @property
    def token(self) -> Optional[str]:
        """
        API token for your dbt Cloud. Instead of setting the parameter, you can set the environment variable `DBT_CLOUD_TOKEN`
        """
        return __config__.get('token') or _utilities.get_env('DBT_CLOUD_TOKEN')

