name: main

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  prerequisites:
    permissions:
      pull-requests: write
    uses: pulumiverse/infra/.github/workflows/provider-prerequisites.yaml@actions-workflows-v0.0.4
    with:
      provider: dbtcloud
      goversion: 1.21.x
  build:
    needs: prerequisites
    uses: pulumiverse/infra/.github/workflows/provider-build-sdk.yaml@actions-workflows-v0.0.4
    with:
      provider: dbtcloud
      goversion: 1.21.x
      dotnetversion: 6.0
      nodeversion: 20.x
      pythonversion: 3.9
