// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ## Import
 *
 * Import using a project ID and credential ID found in the URL or via the API.
 *
 * ```sh
 * $ pulumi import dbtcloud:index/fabricCredential:FabricCredential my_fabric_credential "project_id:credential_id"
 * ```
 *
 * ```sh
 * $ pulumi import dbtcloud:index/fabricCredential:FabricCredential my_fabric_credential 12345:6789
 * ```
 */
export class FabricCredential extends pulumi.CustomResource {
    /**
     * Get an existing FabricCredential resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FabricCredentialState, opts?: pulumi.CustomResourceOptions): FabricCredential {
        return new FabricCredential(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'dbtcloud:index/fabricCredential:FabricCredential';

    /**
     * Returns true if the given object is an instance of FabricCredential.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FabricCredential {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FabricCredential.__pulumiType;
    }

    /**
     * Fabric adapter ID for the credential
     */
    public readonly adapterId!: pulumi.Output<number>;
    /**
     * The client ID of the Azure Active Directory service principal. This is only used when connecting to Azure SQL with an AAD service principal.
     */
    public readonly clientId!: pulumi.Output<string | undefined>;
    /**
     * The client secret of the Azure Active Directory service principal. This is only used when connecting to Azure SQL with an AAD service principal.
     */
    public readonly clientSecret!: pulumi.Output<string | undefined>;
    /**
     * The system Fabric credential ID
     */
    public /*out*/ readonly credentialId!: pulumi.Output<number>;
    /**
     * The password for the account to connect to. Only used when connection with AD user/pass
     */
    public readonly password!: pulumi.Output<string | undefined>;
    /**
     * Project ID to create the Fabric credential in
     */
    public readonly projectId!: pulumi.Output<number>;
    /**
     * The schema where to create the dbt models
     */
    public readonly schema!: pulumi.Output<string>;
    /**
     * Optionally set this to the principal who should own the schemas created by dbt
     */
    public readonly schemaAuthorization!: pulumi.Output<string | undefined>;
    /**
     * The tenant ID of the Azure Active Directory instance. This is only used when connecting to Azure SQL with a service principal.
     */
    public readonly tenantId!: pulumi.Output<string | undefined>;
    /**
     * The username of the Fabric account to connect to. Only used when connection with AD user/pass
     */
    public readonly user!: pulumi.Output<string | undefined>;

    /**
     * Create a FabricCredential resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FabricCredentialArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FabricCredentialArgs | FabricCredentialState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FabricCredentialState | undefined;
            resourceInputs["adapterId"] = state ? state.adapterId : undefined;
            resourceInputs["clientId"] = state ? state.clientId : undefined;
            resourceInputs["clientSecret"] = state ? state.clientSecret : undefined;
            resourceInputs["credentialId"] = state ? state.credentialId : undefined;
            resourceInputs["password"] = state ? state.password : undefined;
            resourceInputs["projectId"] = state ? state.projectId : undefined;
            resourceInputs["schema"] = state ? state.schema : undefined;
            resourceInputs["schemaAuthorization"] = state ? state.schemaAuthorization : undefined;
            resourceInputs["tenantId"] = state ? state.tenantId : undefined;
            resourceInputs["user"] = state ? state.user : undefined;
        } else {
            const args = argsOrState as FabricCredentialArgs | undefined;
            if ((!args || args.adapterId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'adapterId'");
            }
            if ((!args || args.projectId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if ((!args || args.schema === undefined) && !opts.urn) {
                throw new Error("Missing required property 'schema'");
            }
            resourceInputs["adapterId"] = args ? args.adapterId : undefined;
            resourceInputs["clientId"] = args ? args.clientId : undefined;
            resourceInputs["clientSecret"] = args?.clientSecret ? pulumi.secret(args.clientSecret) : undefined;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["projectId"] = args ? args.projectId : undefined;
            resourceInputs["schema"] = args ? args.schema : undefined;
            resourceInputs["schemaAuthorization"] = args ? args.schemaAuthorization : undefined;
            resourceInputs["tenantId"] = args ? args.tenantId : undefined;
            resourceInputs["user"] = args ? args.user : undefined;
            resourceInputs["credentialId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["clientSecret", "password"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(FabricCredential.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering FabricCredential resources.
 */
export interface FabricCredentialState {
    /**
     * Fabric adapter ID for the credential
     */
    adapterId?: pulumi.Input<number>;
    /**
     * The client ID of the Azure Active Directory service principal. This is only used when connecting to Azure SQL with an AAD service principal.
     */
    clientId?: pulumi.Input<string>;
    /**
     * The client secret of the Azure Active Directory service principal. This is only used when connecting to Azure SQL with an AAD service principal.
     */
    clientSecret?: pulumi.Input<string>;
    /**
     * The system Fabric credential ID
     */
    credentialId?: pulumi.Input<number>;
    /**
     * The password for the account to connect to. Only used when connection with AD user/pass
     */
    password?: pulumi.Input<string>;
    /**
     * Project ID to create the Fabric credential in
     */
    projectId?: pulumi.Input<number>;
    /**
     * The schema where to create the dbt models
     */
    schema?: pulumi.Input<string>;
    /**
     * Optionally set this to the principal who should own the schemas created by dbt
     */
    schemaAuthorization?: pulumi.Input<string>;
    /**
     * The tenant ID of the Azure Active Directory instance. This is only used when connecting to Azure SQL with a service principal.
     */
    tenantId?: pulumi.Input<string>;
    /**
     * The username of the Fabric account to connect to. Only used when connection with AD user/pass
     */
    user?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a FabricCredential resource.
 */
export interface FabricCredentialArgs {
    /**
     * Fabric adapter ID for the credential
     */
    adapterId: pulumi.Input<number>;
    /**
     * The client ID of the Azure Active Directory service principal. This is only used when connecting to Azure SQL with an AAD service principal.
     */
    clientId?: pulumi.Input<string>;
    /**
     * The client secret of the Azure Active Directory service principal. This is only used when connecting to Azure SQL with an AAD service principal.
     */
    clientSecret?: pulumi.Input<string>;
    /**
     * The password for the account to connect to. Only used when connection with AD user/pass
     */
    password?: pulumi.Input<string>;
    /**
     * Project ID to create the Fabric credential in
     */
    projectId: pulumi.Input<number>;
    /**
     * The schema where to create the dbt models
     */
    schema: pulumi.Input<string>;
    /**
     * Optionally set this to the principal who should own the schemas created by dbt
     */
    schemaAuthorization?: pulumi.Input<string>;
    /**
     * The tenant ID of the Azure Active Directory instance. This is only used when connecting to Azure SQL with a service principal.
     */
    tenantId?: pulumi.Input<string>;
    /**
     * The username of the Fabric account to connect to. Only used when connection with AD user/pass
     */
    user?: pulumi.Input<string>;
}
