// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getBigQueryCredential(args: GetBigQueryCredentialArgs, opts?: pulumi.InvokeOptions): Promise<GetBigQueryCredentialResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("dbtcloud:index/getBigQueryCredential:getBigQueryCredential", {
        "credentialId": args.credentialId,
        "projectId": args.projectId,
    }, opts);
}

/**
 * A collection of arguments for invoking getBigQueryCredential.
 */
export interface GetBigQueryCredentialArgs {
    /**
     * Credential ID
     */
    credentialId: number;
    /**
     * Project ID
     */
    projectId: number;
}

/**
 * A collection of values returned by getBigQueryCredential.
 */
export interface GetBigQueryCredentialResult {
    /**
     * Credential ID
     */
    readonly credentialId: number;
    /**
     * Default dataset name
     */
    readonly dataset: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Whether the BigQuery credential is active
     */
    readonly isActive: boolean;
    /**
     * Number of threads to use
     */
    readonly numThreads: number;
    /**
     * Project ID
     */
    readonly projectId: number;
}
export function getBigQueryCredentialOutput(args: GetBigQueryCredentialOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetBigQueryCredentialResult> {
    return pulumi.output(args).apply((a: any) => getBigQueryCredential(a, opts))
}

/**
 * A collection of arguments for invoking getBigQueryCredential.
 */
export interface GetBigQueryCredentialOutputArgs {
    /**
     * Credential ID
     */
    credentialId: pulumi.Input<number>;
    /**
     * Project ID
     */
    projectId: pulumi.Input<number>;
}
