// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * @deprecated Do not use! This resource is mapped from the legacy Terraform `dbt_cloud_`-prefixed resource/datasource
 */
export class LegacyEnvironmentVariable extends pulumi.CustomResource {
    /**
     * Get an existing LegacyEnvironmentVariable resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: LegacyEnvironmentVariableState, opts?: pulumi.CustomResourceOptions): LegacyEnvironmentVariable {
        pulumi.log.warn("LegacyEnvironmentVariable is deprecated: Do not use! This resource is mapped from the legacy Terraform `dbt_cloud_`-prefixed resource/datasource")
        return new LegacyEnvironmentVariable(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'dbtcloud:index/legacyEnvironmentVariable:LegacyEnvironmentVariable';

    /**
     * Returns true if the given object is an instance of LegacyEnvironmentVariable.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is LegacyEnvironmentVariable {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === LegacyEnvironmentVariable.__pulumiType;
    }

    /**
     * Map from environment names to respective variable value, a special key `project` should be set for the project default
     * variable value. This field is not set as sensitive so take precautions when using secret environment variables.
     */
    public readonly environmentValues!: pulumi.Output<{[key: string]: any}>;
    /**
     * Name for the variable, must be unique within a project, must be prefixed with 'DBT_'
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Project for the variable to be created in
     */
    public readonly projectId!: pulumi.Output<number>;

    /**
     * Create a LegacyEnvironmentVariable resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    /** @deprecated Do not use! This resource is mapped from the legacy Terraform `dbt_cloud_`-prefixed resource/datasource */
    constructor(name: string, args: LegacyEnvironmentVariableArgs, opts?: pulumi.CustomResourceOptions)
    /** @deprecated Do not use! This resource is mapped from the legacy Terraform `dbt_cloud_`-prefixed resource/datasource */
    constructor(name: string, argsOrState?: LegacyEnvironmentVariableArgs | LegacyEnvironmentVariableState, opts?: pulumi.CustomResourceOptions) {
        pulumi.log.warn("LegacyEnvironmentVariable is deprecated: Do not use! This resource is mapped from the legacy Terraform `dbt_cloud_`-prefixed resource/datasource")
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as LegacyEnvironmentVariableState | undefined;
            resourceInputs["environmentValues"] = state ? state.environmentValues : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["projectId"] = state ? state.projectId : undefined;
        } else {
            const args = argsOrState as LegacyEnvironmentVariableArgs | undefined;
            if ((!args || args.environmentValues === undefined) && !opts.urn) {
                throw new Error("Missing required property 'environmentValues'");
            }
            if ((!args || args.projectId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            resourceInputs["environmentValues"] = args ? args.environmentValues : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["projectId"] = args ? args.projectId : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(LegacyEnvironmentVariable.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering LegacyEnvironmentVariable resources.
 */
export interface LegacyEnvironmentVariableState {
    /**
     * Map from environment names to respective variable value, a special key `project` should be set for the project default
     * variable value. This field is not set as sensitive so take precautions when using secret environment variables.
     */
    environmentValues?: pulumi.Input<{[key: string]: any}>;
    /**
     * Name for the variable, must be unique within a project, must be prefixed with 'DBT_'
     */
    name?: pulumi.Input<string>;
    /**
     * Project for the variable to be created in
     */
    projectId?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a LegacyEnvironmentVariable resource.
 */
export interface LegacyEnvironmentVariableArgs {
    /**
     * Map from environment names to respective variable value, a special key `project` should be set for the project default
     * variable value. This field is not set as sensitive so take precautions when using secret environment variables.
     */
    environmentValues: pulumi.Input<{[key: string]: any}>;
    /**
     * Name for the variable, must be unique within a project, must be prefixed with 'DBT_'
     */
    name?: pulumi.Input<string>;
    /**
     * Project for the variable to be created in
     */
    projectId: pulumi.Input<number>;
}
