// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function legacyGetWebhook(args: LegacyGetWebhookArgs, opts?: pulumi.InvokeOptions): Promise<LegacyGetWebhookResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("dbtcloud:index/legacyGetWebhook:LegacyGetWebhook", {
        "webhookId": args.webhookId,
    }, opts);
}

/**
 * A collection of arguments for invoking LegacyGetWebhook.
 */
export interface LegacyGetWebhookArgs {
    webhookId: string;
}

/**
 * A collection of values returned by LegacyGetWebhook.
 */
export interface LegacyGetWebhookResult {
    readonly accountIdentifier: string;
    readonly active: boolean;
    readonly clientUrl: string;
    readonly description: string;
    readonly eventTypes: string[];
    readonly httpStatusCode: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly jobIds: number[];
    readonly name: string;
    readonly webhookId: string;
}
export function legacyGetWebhookOutput(args: LegacyGetWebhookOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<LegacyGetWebhookResult> {
    return pulumi.output(args).apply((a: any) => legacyGetWebhook(a, opts))
}

/**
 * A collection of arguments for invoking LegacyGetWebhook.
 */
export interface LegacyGetWebhookOutputArgs {
    webhookId: pulumi.Input<string>;
}
