// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function legacyGetPrivatelinkEndpoint(args?: LegacyGetPrivatelinkEndpointArgs, opts?: pulumi.InvokeOptions): Promise<LegacyGetPrivatelinkEndpointResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("dbtcloud:index/legacyGetPrivatelinkEndpoint:LegacyGetPrivatelinkEndpoint", {
        "name": args.name,
        "privateLinkEndpointUrl": args.privateLinkEndpointUrl,
    }, opts);
}

/**
 * A collection of arguments for invoking LegacyGetPrivatelinkEndpoint.
 */
export interface LegacyGetPrivatelinkEndpointArgs {
    name?: string;
    privateLinkEndpointUrl?: string;
}

/**
 * A collection of values returned by LegacyGetPrivatelinkEndpoint.
 */
export interface LegacyGetPrivatelinkEndpointResult {
    readonly cidrRange: string;
    readonly id: string;
    readonly name?: string;
    readonly privateLinkEndpointUrl?: string;
    readonly state: number;
    readonly type: string;
}
export function legacyGetPrivatelinkEndpointOutput(args?: LegacyGetPrivatelinkEndpointOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<LegacyGetPrivatelinkEndpointResult> {
    return pulumi.output(args).apply((a: any) => legacyGetPrivatelinkEndpoint(a, opts))
}

/**
 * A collection of arguments for invoking LegacyGetPrivatelinkEndpoint.
 */
export interface LegacyGetPrivatelinkEndpointOutputArgs {
    name?: pulumi.Input<string>;
    privateLinkEndpointUrl?: pulumi.Input<string>;
}
