// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/** @deprecated Do not use! This resource is mapped from the legacy Terraform `dbt_cloud_`-prefixed resource/datasource */
export function legacyGetUser(args: LegacyGetUserArgs, opts?: pulumi.InvokeOptions): Promise<LegacyGetUserResult> {
    pulumi.log.warn("legacyGetUser is deprecated: Do not use! This resource is mapped from the legacy Terraform `dbt_cloud_`-prefixed resource/datasource")

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("dbtcloud:index/legacyGetUser:LegacyGetUser", {
        "email": args.email,
    }, opts);
}

/**
 * A collection of arguments for invoking LegacyGetUser.
 */
export interface LegacyGetUserArgs {
    email: string;
}

/**
 * A collection of values returned by LegacyGetUser.
 */
export interface LegacyGetUserResult {
    readonly email: string;
    readonly id: number;
}
/** @deprecated Do not use! This resource is mapped from the legacy Terraform `dbt_cloud_`-prefixed resource/datasource */
export function legacyGetUserOutput(args: LegacyGetUserOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<LegacyGetUserResult> {
    return pulumi.output(args).apply((a: any) => legacyGetUser(a, opts))
}

/**
 * A collection of arguments for invoking LegacyGetUser.
 */
export interface LegacyGetUserOutputArgs {
    email: pulumi.Input<string>;
}
